apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: gateway
    spec:
      serviceAccountName: burger-sa
      containers:
        - name: gateway
          image: europe-west6-docker.pkg.dev/burger-order-485523/docker-repo/gateway:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            # Gateway Settings
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: GATEWAY_INTERNAL_PORT
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: GATEWAY_INTERNAL_PORT

            # Database Settings
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: POSTGRES_PASSWORD

            # OAuth2 Settings
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: GOOGLE_CLIENT_SECRET

            # Redis Settings
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: burger-secrets-sync
                  key: REDIS_PASSWORD

            - name: BURGER_API_HOST
              value: "burger-order-api"
            - name: BURGER_API_PORT
              value: "8081"
            - name: BURGER_UI_HOST
              value: "burger-order-ui"
            - name: BURGER_UI_PORT
              value: "8082"
          livenessProbe:
            exec:
              command:
                - wget -q --spider http://localhost:8080/ping || exit 1
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - name: "80"
      port: 80
      targetPort: 8080
  selector:
    io.kompose.service: gateway
