apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: burger-secrets-provider
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/731958749381/secrets/GATEWAY_INTERNAL_PORT/versions/latest"
        path: "gateway-internal-port"
      - resourceName: "projects/731958749381/secrets/POSTGRES_HOST/versions/latest"
        path: "pg-host"
      - resourceName: "projects/731958749381/secrets/POSTGRES_PORT/versions/latest"
        path: "pg-port"
      - resourceName: "projects/731958749381/secrets/POSTGRES_DB/versions/latest"
        path: "pg-db"
      - resourceName: "projects/731958749381/secrets/POSTGRES_USER/versions/latest"
        path: "pg-user"
      - resourceName: "projects/731958749381/secrets/POSTGRES_PASSWORD/versions/latest"
        path: "pg-pass"
      - resourceName: "projects/731958749381/secrets/GOOGLE_CLIENT_ID/versions/latest"
        path: "google-client-id"
      - resourceName: "projects/731958749381/secrets/GOOGLE_CLIENT_SECRET/versions/latest"
        path: "google-client-secret"
      - resourceName: "projects/731958749381/secrets/REDIS_PASSWORD/versions/latest"
        path: "redis-pass"
      - resourceName: "projects/731958749381/secrets/ELASTIC_PASSWORD/versions/latest"
        path: "elastic-pass"
      - resourceName: "projects/731958749381/secrets/RABBITMQ_USER/versions/latest"
        path: "rabbit-user"
      - resourceName: "projects/731958749381/secrets/RABBITMQ_PASSWORD/versions/latest"
        path: "rabbit-pass"
      - resourceName: "projects/731958749381/secrets/EMAIL_USERNAME/versions/latest"
        path: "email-username"
      - resourceName: "projects/731958749381/secrets/EMAIL_PASSWORD/versions/latest"
        path: "email-password"
      - resourceName: "projects/731958749381/secrets/ORDER_REPORT_EMAIL_RECIPIENT/versions/latest"
        path: "order-report-email-recipient"
  secretObjects:
    - secretName: burger-secrets-sync
      type: Opaque
      data:
        - objectName: "gateway-internal-port"
          key: "GATEWAY_INTERNAL_PORT"
        - objectName: "pg-host"
          key: "POSTGRES_HOST"
        - objectName: "pg-port"
          key: "POSTGRES_PORT"
        - objectName: "pg-db"
          key: "POSTGRES_DB"
        - objectName: "pg-user"
          key: "POSTGRES_USER"
        - objectName: "pg-pass"
          key: "POSTGRES_PASSWORD"
        - objectName: "google-client-id"
          key: "GOOGLE_CLIENT_ID"
        - objectName: "google-client-secret"
          key: "GOOGLE_CLIENT_SECRET"
        - objectName: "redis-pass"
          key: "REDIS_PASSWORD"
        - objectName: "elastic-pass"
          key: "ELASTIC_PASSWORD"
        - objectName: "rabbit-user"
          key: "RABBITMQ_USER"
        - objectName: "rabbit-pass"
          key: "RABBITMQ_PASSWORD"
        - objectName: "email-username"
          key: "EMAIL_USERNAME"
        - objectName: "email-password"
          key: "EMAIL_PASSWORD"
        - objectName: "order-report-email-recipient"
          key: "ORDER_REPORT_EMAIL_RECIPIENT"
